export const ALLOWED_COUNTRIES = [
  'South Korea',
  'Japan',
  'Denmark',
  'Belgium',
  'Slovenia',
  'Netherlands',
  'Germany',
  'Finland',
  'Norway',
  'Ireland',
  'Singapore',
  'France',
  'China',
  'Hong Kong',
  'Sweden',
  'United Kingdom',
  'Australia',
  'Iceland',
  'Canada',
  'India',
  'Spain',
  'IB Model',
  'UN SDG 4'
];

export const ALLOWED_SUBJECTS = [
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Science',
  'English',
  'Environmental Science',
  'Earth Science',
  'Astronomy',
  'Computer Science',
  'Artificial Intelligence',
  'Information Technology',
  'Engineering',
  'Medicine and Health Sciences',
  'Economics',
  'Business Studies',
  'Accounting',
  'Finance',
  'Commerce',
  'Political Science',
  'International Relations',
  'History',
  'Geography',
  'Sociology',
  'Psychology',
  'Philosophy',
  'Law',
  'Civics',
  'Education',
  'Anthropology',
  'Archaeology',
  'Statistics',
  'Data Science',
  'Literature',
  'Languages',
  'Linguistics',
  'Journalism',
  'Media Studies',
  'Communication',
  'Fine Arts',
  'Visual Arts',
  'Music',
  'Performing Arts',
  'Design',
  'Architecture',
  'Agriculture',
  'Veterinary Science',
  'Sports Science',
  'Physical Education',
  'Hospitality',
  'Tourism',
  'General',
  'Interdisciplinary',
  'Vocational Studies'
];
